# routes.yaml

# Rediriger la racine vers la locale par défaut /fr
root_redirect:
  path: /
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
  defaults:
    route: app_accueil
    permanent: true
    _locale: fr

# Chargement des controllers avec prefix par locale
controllers:
  resource: ../src/Controller/
  type: attribute
  prefix:
    fr: /fr
    en: /en
    ar: /ar
